# Generated by Django 6.0.5 on 2026-06-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='societymembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='societymembership',
            name='wing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='societymembership',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Admin'), ('worker', 'Worker'), ('resident', 'Resident')], max_length=20),
        ),
        migrations.AlterField(
            model_name='societymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='societymembership',
            unique_together={('user', 'society', 'wing', 'flat_number')},
        ),
    ]
