# Generated by Django 6.0.5 on 2026-05-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0002_servicebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='estimated_arrival',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='worker_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='worker_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Worker Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
