# Generated by Django 6.0.5 on 2026-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0003_servicebooking_estimated_arrival_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('emergency', 'Emergency')], default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
