# Generated by Django 6.0.5 on 2026-05-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0007_society_user_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='society',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='fixora_app.society'),
        ),
    ]
