# Generated by Django 6.0.5 on 2026-05-29 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0009_complaint_assigned_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooking',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='completion_image',
            field=models.ImageField(blank=True, null=True, upload_to='completed_works/'),
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='worker_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
