# Generated by Django 6.0.5 on 2026-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0011_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'System Super Admin'), ('admin', 'Admin'), ('resident', 'Resident'), ('worker', 'Worker')], default='resident', max_length=15),
        ),
    ]
