# Generated by Django 6.0.5 on 2026-06-19 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixora_app', '0012_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.CharField(max_length=20)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fixora_app.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'society')},
            },
        ),
    ]
